name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  branches:
    include:
    - main

variables:
  - group: azure-container-app

stages :

  - stage: create_container_environment
    jobs:
      - job: "deploy_app"
        steps:
          - task: AzureCLI@2
            displayName: 'Create container app environment'
            inputs:
              azureSubscription: 'KevinLi-Internal(ed5ebdf4-3f16-4970-8666-b0b3803c727e)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az extension add \
                --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.2-py2.py3-none-any.whl --yes

                az provider register --namespace Microsoft.Web

                RESOURCE_GROUP="azure-container-rg"
                LOCATION="eastasia"
                LOG_ANALYTICS_WORKSPACE="klacrcontainersla"
                CONTAINERAPPS_ENVIRONMENT="kl-environment"

                LOG_ANALYTICS_WORKSPACE_CLIENT_ID=`az monitor log-analytics workspace show --query customerId -g $RESOURCE_GROUP -n $LOG_ANALYTICS_WORKSPACE -o tsv | tr -d '[:space:]'`
                LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET=`az monitor log-analytics workspace get-shared-keys --query primarySharedKey -g $RESOURCE_GROUP -n $LOG_ANALYTICS_WORKSPACE -o tsv | tr -d '[:space:]'`

                az containerapp env create \
                -n $CONTAINERAPPS_ENVIRONMENT \
                -g $RESOURCE_GROUP \
                --logs-workspace-id $LOG_ANALYTICS_WORKSPACE_CLIENT_ID \
                --logs-workspace-key $LOG_ANALYTICS_WORKSPACE_CLIENT_SECRET \
                -l $LOCATION



  - stage: deploy_container_app
    dependsOn: [create_container_environment]
    jobs:
      - job: "deploy_app"
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy app to Container App'
            inputs:
              azureSubscription: 'KevinLi-Internal(ed5ebdf4-3f16-4970-8666-b0b3803c727e)'
              scriptType: bash
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                #!/bin/bash
                az extension add \
                --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.2-py2.py3-none-any.whl --yes

                az provider register --namespace Microsoft.Web

                RESOURCE_GROUP="azure-container-rg"
                LOG_ANALYTICS_WORKSPACE="klacrcontainersla"
                CONTAINERAPPS_ENVIRONMENT="kl-environment"
                LOCATION="eastasia"
                AZP_URL="https://dev.azure.com/GitHubDeploy"
                AZP_TOKEN=$(pattoken)
                AZP_AGENT_NAME=devopsagentnew
                AZP_POOL=containerapp-pool
                AZP_POOL_ID=65
                REGISTRY_USERNAME=klacrcontainers
                REGISTRY_PASSWORD=$(acrpassword)
                REGISTRY_LOGIN_SERVER=klacrcontainers.azurecr.io
                IMAGE=klacrcontainers.azurecr.io/sampleapp:v1
                
                CONTAINER_APP_NAME="azuredevops-agent"
                MIN_REPLICAS="1"
                MAX_REPLICAS="3"
                CPU="1.75"
                MEMORY="3.5Gi"

                  az deployment group create \
                    --resource-group $RESOURCE_GROUP \
                    --template-file "containerapp/containerapp.json" \
                    --parameters \
                        environment_name="$CONTAINERAPPS_ENVIRONMENT" \
                        location="$LOCATION" \
                        azp_url="$AZP_URL" \
                        azp_token="$AZP_TOKEN" \
                        azp_pool="$AZP_POOL" \
                        azp_poolId="$AZP_POOL_ID" \
                        REGISTRY_LOGIN_SERVER=$REGISTRY_LOGIN_SERVER \
                        REGISTRY_USERNAME=$REGISTRY_USERNAME \
                        REGISTRY_PASSWORD=$REGISTRY_PASSWORD \
                        IMAGE=$IMAGE \
                        MIN_REPLICAS=$MIN_REPLICAS \
                        MAX_REPLICAS=$MAX_REPLICAS \
                        CPU=$CPU \
                        MEMORY=$MEMORY \
                        CONTAINER_APP_NAME=$CONTAINER_APP_NAME
